### ISSUE TITLE
Add Travis and Codeclimate badges and services

### ISSUE THREAD

**Issue by spaghetticode** [mikamai/dotenv_sekrets#1]
@nicolaracco can you please add this repo to mikamai's codeclimate? 
BTW I have refreshed travis repos list a couple of times, but this one is still not listed...

**Comment by nicolaracco** [comment]
- [Travis](https://travis-ci.org/mikamai/dotenv_sekrets)
- [CodeClimate](https://codeclimate.com/github/mikamai/dotenv_sekrets)
